### ISSUE TITLE
Mac 转换 PDF 出现错误

### ISSUE THREAD

**Issue by chezhongkun** [ganeshh123/notion-pdf-export#17] opened 2020-11-01 11:06 UTC
Mac转换PDF文件的时候出现了错误
不知道怎么解决
如下：
/Users/time/Downloads/notion-pdf-export_mac_1.3.0/notion-pdf-export: line 3: cd: /Users/time/Downloads/notion-pdf-export_mac_1.3.0/notion-pdf-export/..: Not a directory
/Users/time/Downloads/notion-pdf-export_mac_1.3.0/notion-pdf-export: line 5: ./npe: No such file or directory
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by ganeshh123** [comment] 2020-11-01 19:31
A temporary workaround is to open the Terminal in the notion-pdf-export folder and then:
`./npe`

**Comment by carhuacm** [comment] 2021-03-30 16:02
hi, thank for ur help. i'm having the same program, but i coudn't fix it. could u show me how to fix it :(?:

% /Users/ccm/Desktop/notion-pdf-export_mac_1.3.0/notion-pdf-export ; exit;
/Users/ccm/Desktop/notion-pdf-export_mac_1.3.0/notion-pdf-export: line 3: cd: /Users/ccm/Desktop/notion-pdf-export_mac_1.3.0/notion-pdf-export/..: Not a directory
/Users/ccm/Desktop/notion-pdf-export_mac_1.3.0/notion-pdf-export: line 5: ./npe: No such file or directory

[Proceso completado]

**Comment by ganeshh123** [comment] 2021-03-30 18:36
> hi, thank for ur help. i'm having the same program, but i coudn't fix it. could u show me how to fix it :(?:
> 
> % /Users/ccm/Desktop/notion-pdf-export_mac_1.3.0/notion-pdf-export ; exit;
> /Users/ccm/Desktop/notion-pdf-export_mac_1.3.0/notion-pdf-export: line 3: cd: /Users/ccm/Desktop/notion-pdf-export_mac_1.3.0/notion-pdf-export/..: Not a directory
> /Users/ccm/Desktop/notion-pdf-export_mac_1.3.0/notion-pdf-export: line 5: ./npe: No such file or directory
> 
> [Proceso completado]

@carhuacm could you post a screenshot please so I can get some context? Thanks

**Comment by carhuacm** [comment] 2021-03-30 22:28
![Captura de Pantalla 2021-03-30 a la(s) 19 26 57](https://user-images.githubusercontent.com/81638415/113064795-1cd47000-918e-11eb-95c1-75950b0a214e.png)
this is what appear when I do all the process

**Comment by ganeshh123** [comment] 2021-03-30 22:32
> ![Captura de Pantalla 2021-03-30 a la(s) 19 26 57](https://user-images.githubusercontent.com/81638415/113064795-1cd47000-918e-11eb-95c1-75950b0a214e.png)
> this is what appear when I do all the process

I meant can you show the folder where you are running it. If not, run the command `ls -a -l` and show the output. It seems to not be finding the `npe` file

**Comment by ganeshh123** [comment] 2021-04-23 10:54
Duplicate of #22

**Comment by ganeshh123** [comment] 2021-04-23 10:55
Duplicate of #22

**Closed by ganeshh123** 2021-04-23 10:55 UTC
